### ISSUE TITLE
pvt_v2

### ISSUE THREAD

**Issue by HappyAndSad123** [whyandbecause/SDRNet#2]
老师，请问一下，可以给一下pvt_v2您自己调的源码吗？

**Comment by whyandbecause** [comment]
您好，我们这篇论文用的backbone是原版的pvt_v2，和其他用pvt_v2作为backbone的论文用的是一样的源码，代码放在lib目录下，可以直接调用。

**Comment by whyandbecause** [comment]
> 老师，请问一下，可以给一下pvt_v2您自己调的源码吗？
您好，我们这篇论文用的backbone是原版的pvt_v2，和其他用pvt_v2作为backbone的论文用的是一样的源码，代码放在lib目录下，可以直接调用。

**Comment by whyandbecause** [comment]
> 老师，请问一下，可以给一下pvt_v2您自己调的源码吗？

您好，我们这篇论文用的backbone是原版的pvt_v2，和其他用pvt_v2作为backbone的论文用的是一样的源码，代码放在lib目录下，可以直接调用。
